# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: AML-playground
version: 1.0.0
summary: Azure Machine Learning with dependencies
description: Deployed AML with Storage, Key Vault, ACR, AppInsights
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: location
    name: Azure region/location
    type: string
    description: Azure region/location
    default: 'uksouth'
    allowed:
      - 'uksouth'
      - 'ukwest'
  - id: vmSize
    name: AML workspace VM SKU
    type: string
    description: The Azure VM SKU you want to base the AML workspace on, e.g. Standard_D4_v3
    default: 'Standard_D4_v3'
